### ISSUE TITLE
The author name is used for the bindle name

### ISSUE THREAD

**Issue by carolynvs** [deislabs/yo-wasm#40]
When I run through `yo wasm`, it suggests my full name "Carolyn Van Slyck" as the author name. It then combines that with the name of the app to suggest the bindle name "Carolyn Van Slyck/myapp" which isn't ideal. I always end up changing the author name to my username, e.g. "carolynvs" to work around it.

I'm not sure if author name _should_ be a username or a full name, but the way it works right now causes trouble later with the bindle name.

**Comment by itowlson** [comment]
The author name is used for things like the Cargo author field which are meant to be full names.  The default bindle _should_ be made identifier-safe (e.g. `carolynvanslyck/myapp`).  Which is still not ideal.  I guess I could prompt for the bindle prefix and then prompt again for the bindle name, which would make it easier to override the first while defaulting the second, but I'm not sure that's a great improvement.

**Comment by carolynvs** [comment]
Oh weird! Earlier I was seeing it default to "Carolyn Van Slyck/myapp" but I just updated and tried again and it's doing "carolynvanslyck/myapp". Not sure what happened but that works for me. Sorry to bug ya!
