### ISSUE TITLE
Change default domain name 

### ISSUE THREAD

**Issue by simongdavies** [deislabs/yo-wasm#67]
Domain name currently defaults to <modulename>.localhost, we should consider changing this to <modulname>.hippofactory.io as this will resolve to 127.0.0.1 and .localhost does not seem to work on all platforms.

**Comment by itowlson** [comment]
The default in the code is `hippofactory.io`.  Did you set `HIPPO_URL` to `localhost`?

**Comment by simongdavies** [comment]
Ah , I see, I used release version 0.3.0, looks like this is in 0.4.0
